### ISSUE TITLE
Keyboard interactions

### ISSUE THREAD

**Issue by NickGreen** [scripting/feedlandBlogrollToolkit#2]
Keyboard interactions aren't currently working as expected on https://feedland.blog/blogroll-wp-plugin-test/

### Expected behavior

When the Blogroll div is in focus, we should be able to click up and down with the keyboard to navigate, and press enter to open each line.

### Observed behavior

The keyboard interactions aren't navigating within the `#BlogrollContainer` div.

### Details

- If we force the focus state on that div within the inspector, it works.
- isBlogrollFocus() is evaluating to false because the div isn't in focus

### Solution
- We need to add tabindex attribute

Change this:
```PHP
function feedland_blogroll_shortcode(): string {
	return '<div id="divBlogrollContainer"></div><script>$=jQuery;blogroll(BLOGROLL_OPTIONS);</script>';
}
```

to this:
```PHP
function feedland_blogroll_shortcode(): string {
	return '<div id="divBlogrollContainer" tabindex="0"></div><script>$=jQuery;blogroll(BLOGROLL_OPTIONS);</script>';
}
```

**Comment by scripting** [comment]
Good report. 

I didn't write explicit instructions, I probably should, but the [example code](https://github.com/scripting/feedlandBlogrollToolkit/blob/main/index.html#L43) does have the tabindex attribute.



```html
<div class="divBlogrollContainer" id="idBlogrollContainer" tabindex="0">
		</div>
```

**Comment by NickGreen** [comment]
Perfect. Looks like that was missed. We've got that added now, so closing this out.
